import * as XLSX from 'xlsx';
import type { CustomerSnapshot, Mapping, ParsedTable, ValidationReport } from './types.ts';
export const FIELD_SPECS=[['customerId','Customer ID',true],['snapshotDate','Snapshot date',true],['renewalDate','Renewal date',false],['monthlyRevenue','Monthly revenue',true],['planTier','Plan tier',false],['usage30d','Usage 30d',true],['usagePrev30d','Usage previous 30d',true],['tickets30d','Tickets 30d',true],['latePayments90d','Late payments 90d',true],['tenureMonths','Tenure months',true],['activeDays30d','Active days 30d',true],['churned','Churned label (0/1)',true]] as const;
const aliases:Record<keyof Mapping,string[]>={customerId:['customer_id','customer','account_id','client_id','id'],snapshotDate:['snapshot_date','as_of_date','date','observation_date'],renewalDate:['renewal_date','contract_end','renewal'],monthlyRevenue:['monthly_revenue','mrr','revenue','arr_monthly','monthly_value'],planTier:['plan_tier','plan','tier','segment'],usage30d:['usage_30d','usage30d','events_30d','logins_30d'],usagePrev30d:['usage_prev_30d','previous_usage_30d','usage_prior_30d','events_prev_30d'],tickets30d:['tickets_30d','support_tickets_30d','tickets'],latePayments90d:['late_payments_90d','late_payments','payment_delays_90d'],tenureMonths:['tenure_months','tenure','months_active'],activeDays30d:['active_days_30d','active_days','days_active_30d'],churned:['churned','churn','is_churned','target']};
function normalize(v:string){return v.trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');}
export function inferMapping(columns:string[]):Mapping{const out={} as Mapping;for(const key of Object.keys(aliases) as Array<keyof Mapping>){out[key]=columns.find(c=>aliases[key].includes(normalize(c)))??'';}return out;}
export async function parseFile(file:File):Promise<ParsedTable>{const buf=await file.arrayBuffer();const book=XLSX.read(buf,{type:'array',cellDates:false});const sheet=book.Sheets[book.SheetNames[0]];const rows=XLSX.utils.sheet_to_json<Record<string,unknown>>(sheet,{defval:null,raw:false});if(!rows.length)throw new Error('No data rows found.');return{fileName:file.name,columns:Object.keys(rows[0]),rows};}
function num(v:unknown){if(v===null||v===undefined||v==='')return NaN;return Number(String(v).replace(/[$,₹€£]/g,''));}
function iso(v:unknown):string|null{if(v===null||v===undefined||v==='')return null;const s=String(v).trim();const d=new Date(s.length===10?`${s}T00:00:00Z`:s);return Number.isNaN(d.valueOf())?null:d.toISOString().slice(0,10);}
export function validateRows(parsed:ParsedTable,m:Mapping):ValidationReport{const required=(FIELD_SPECS.filter(x=>x[2]) as readonly (readonly [keyof Mapping,string,boolean])[]).map(x=>x[0]);const missing=required.filter(k=>!m[k]);if(missing.length)throw new Error(`Map required fields: ${missing.join(', ')}`);const accepted:CustomerSnapshot[]=[];const rejected:Array<{row:number;reason:string}>=[];parsed.rows.forEach((r,i)=>{const date=iso(r[m.snapshotDate]);const renewal=m.renewalDate?iso(r[m.renewalDate]):null;const churn=num(r[m.churned]);const vals={rev:num(r[m.monthlyRevenue]),usage:num(r[m.usage30d]),prev:num(r[m.usagePrev30d]),tickets:num(r[m.tickets30d]),late:num(r[m.latePayments90d]),tenure:num(r[m.tenureMonths]),active:num(r[m.activeDays30d])};const reasons:string[]=[];if(!String(r[m.customerId]??'').trim())reasons.push('missing customer id');if(!date)reasons.push('invalid snapshot date');if(![0,1].includes(churn))reasons.push('churned must be 0 or 1');for(const[k,v]of Object.entries(vals))if(!Number.isFinite(v)||v<0)reasons.push(`invalid ${k}`);if(vals.active>31)reasons.push('active days > 31');if(reasons.length){rejected.push({row:i+2,reason:reasons.join('; ')});return;}accepted.push({customerId:String(r[m.customerId]).trim(),snapshotDate:date!,renewalDate:renewal,monthlyRevenue:vals.rev,planTier:m.planTier?String(r[m.planTier]??'Unspecified'):'Unspecified',usage30d:vals.usage,usagePrev30d:vals.prev,tickets30d:vals.tickets,latePayments90d:vals.late,tenureMonths:vals.tenure,activeDays30d:vals.active,churned:churn});});const warnings:string[]=[];if(accepted.length<100)warnings.push('Small datasets can produce unstable probability estimates; interpret holdout metrics cautiously.');const counts=new Map<string,number>();accepted.forEach(r=>counts.set(r.customerId,(counts.get(r.customerId)??0)+1));if([...counts.values()].every(v=>v===1))warnings.push('Only one snapshot per customer: risk trajectory is unavailable and the time split reflects customer rows rather than longitudinal snapshots.');return{accepted,rejected,warnings};}
export function templateCsv(){return 'customer_id,snapshot_date,renewal_date,monthly_revenue,plan_tier,usage_30d,usage_prev_30d,tickets_30d,late_payments_90d,tenure_months,active_days_30d,churned\nC001,2026-07-31,2026-09-15,420,Pro,38,61,3,1,26,12,0\n';}
